spring:
  application:
    name: microservice-consumer-movie-ribbon
server:
  port: 8010
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule         #以通过这个配置项定制需要的负载均衡规则
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
#    NFLoadBalancerPingClassName:  #用于配置查看服务器是否存活。
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList   #是服务器列表的处理类
