spring:
#  application:
#    name: EUREKA-HA-3
  application:
    name: EUREKA-HA
  profiles:
    active: peer3
server:
  port: 8763
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/