spring:
  application:
    name: microservice-consumer-movie
server:
  port: 7901
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
#      defaultZone: http://user:password123@localhost:8761/eureka
      defaultZone: http://localhost:8761/eureka
#    eureka-server-read-timeout-seconds: 20000
  instance:
    prefer-ip-address: true
    feign:
      hystrix:
        enabled: false
# 解决第一次请求报超时异常的方案：
  hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000